#!/bin/bash
local_sh="$HOME/anaconda3.sh"
wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O $local_sh
bash $local_sh -b -p $HOME/Anaconda3
eval "$($HOME/Anaconda3/bin/conda shell.bash hook)"
conda init
rm $local_sh
source $HOME/.bashrc
